# -*- coding: utf-8 -*-
"""generator_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0QBhOemibeNAmeNi6QUhYXqcL59QBG0
"""

# generator_model.py

import torch
import torch.nn as nn

class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()
        self.label_emb = nn.Embedding(10, 10)
        self.model = nn.Sequential(
            nn.Linear(100 + 10, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 512),
            nn.LeakyReLU(0.2),
            nn.Linear(512, 1024),
            nn.LeakyReLU(0.2),
            nn.Linear(1024, 784),
            nn.Tanh()
        )

    def forward(self, noise, labels):
        x = torch.cat([noise, self.label_emb(labels)], dim=1)
        img = self.model(x)
        return img